/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    locations: Location;
    tours: Tour;
    'case-studies': CaseStudy;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: {
    vi: string;
    en?: string | null;
  };
  blurDataURL?: string | null;
  canhBaoKichThuoc?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    w640?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w1024?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w1600?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w2400?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Những nơi cụ thể được nhắc tới trong bài viết — quán ăn, homestay, chợ phiên. Mỗi địa điểm có trang riêng và dùng lại được ở nhiều tour.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  slug: string;
  name: {
    vi: string;
  };
  /**
   * Tự động lấy từ "Tên địa điểm" ở trên — không cần nhập tay. Dùng để hiển thị trong danh sách và trên đầu trang quản trị.
   */
  displayTitle?: string | null;
  category: 'an-uong' | 'luu-tru' | 'thien-nhien' | 'van-hoa' | 'cho-mua-sam';
  /**
   * Một hoặc hai câu, hiện trên THẺ địa điểm nhúng trong bài viết. Giữ ngắn — thẻ chỉ đủ chỗ cho khoảng hai dòng.
   */
  excerpt: {
    vi: string;
  };
  /**
   * Mỗi dòng là một đoạn văn.
   */
  body: {
    vi: string;
    id?: string | null;
  }[];
  address?: string | null;
  /**
   * URL đầy đủ, ví dụ: https://... — để trống nếu nơi này không có web.
   */
  website?: string | null;
  /**
   * Ảnh đầu tiên được dùng làm ảnh trên thẻ.
   */
  images: (string | Media)[];
  seo: {
    /**
     * Dòng chữ hiện trên tab trình duyệt và trên kết quả tìm kiếm Google. Nên ngắn gọn.
     */
    title: {
      vi: string;
    };
    /**
     * Đoạn tóm tắt hiện dưới tiêu đề trên kết quả tìm kiếm Google và khi chia sẻ link lên Zalo/Facebook.
     */
    description: {
      vi: string;
    };
    ogImage: string | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: string;
  slug: string;
  title: {
    vi: string;
  };
  /**
   * Tự động lấy từ "Tên tour" ở trên — không cần nhập tay. Dùng để hiển thị trong danh sách và trên đầu trang quản trị.
   */
  displayTitle?: string | null;
  tagline: {
    vi: string;
  };
  summary: {
    vi: string;
  };
  durationDays: number;
  /**
   * Nhập số nguyên, không dấu chấm hay dấu phẩy. Ví dụ: 6900000 nghĩa là 6.900.000đ.
   */
  priceFrom: number;
  destinations: {
    vi: string;
    id?: string | null;
  }[];
  heroMedia: string | Media;
  gallery: (string | Media)[];
  itinerary?:
    | {
        title: {
          vi: string;
        };
        description: {
          vi: string;
        };
        /**
         * Chọn 2 ảnh thì chúng xếp thành hai cột. Nhiều hơn 3 ảnh sẽ bị cắt bớt khi hiển thị.
         */
        images?: (string | Media)[] | null;
        /**
         * Hiện thành khối thẻ có ảnh dưới phần mô tả. Chọn từ danh sách Địa điểm đã tạo.
         */
        locations?: (string | Location)[] | null;
        /**
         * Ví dụ: "Ăn ở đâu", "Ngủ ở đâu". Bỏ trống thì dùng nhãn mặc định.
         */
        locationsLabel?: {
          vi?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Những gì khách được hưởng khi mua tour.
   */
  inclusions: {
    vi: string;
    id?: string | null;
  }[];
  /**
   * Những chi phí khách tự lo, không nằm trong giá tour.
   */
  exclusions?:
    | {
        vi: string;
        id?: string | null;
      }[]
    | null;
  notes?: {
    vi?: string | null;
  };
  seo: {
    /**
     * Dòng chữ hiện trên tab trình duyệt và trên kết quả tìm kiếm Google. Nên ngắn gọn.
     */
    title: {
      vi: string;
    };
    /**
     * Đoạn tóm tắt hiện dưới tiêu đề trên kết quả tìm kiếm Google và khi chia sẻ link lên Zalo/Facebook.
     */
    description: {
      vi: string;
    };
    ogImage: string | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Những chuyến đã tổ chức xong, kể lại theo ngày. Đây là phần chứng minh năng lực — không phải sản phẩm đang bán.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  slug: string;
  /**
   * Ngắn, thường là tên nơi đến. Ví dụ: "Hà Giang cho một nhóm 9 người".
   */
  title: {
    vi: string;
  };
  /**
   * Tự động lấy từ "Tên chuyến đi" ở trên — không cần nhập tay. Dùng để hiển thị trong danh sách và trên đầu trang quản trị.
   */
  displayTitle?: string | null;
  /**
   * Một dòng in nghiêng dưới tên. Ví dụ: "Sáu ngày cuối tháng Mười".
   */
  subtitle: {
    vi: string;
  };
  /**
   * Màu riêng của bài này. Chọn khác nhau cho từng chuyến để bốn bài không trông giống hệt nhau.
   */
  accent: 'dat-nung' | 'xanh-reu' | 'chi-lam' | 'tim-man' | 'vang-dat';
  heroImage: string | Media;
  /**
   * Ảnh này bị cắt thành hình TRÒN nên chủ thể phải nằm giữa khung. Bỏ trống thì dùng Ảnh đầu bài — ảnh ngang cắt tròn thường mất hai đầu, nên tốt nhất là chọn riêng một ảnh dọc.
   */
  thumbnail?: (string | null) | Media;
  /**
   * Mỗi dòng là một đoạn văn.
   */
  highlights: {
    vi: string;
    id?: string | null;
  }[];
  /**
   * Mỗi dòng là một việc. Viết ngắn, ở thì quá khứ.
   */
  ourRole: {
    vi: string;
    id?: string | null;
  }[];
  /**
   * Số thứ tự ngày tự sinh theo vị trí trong danh sách — kéo thả để sắp lại, không cần đánh số.
   */
  days: {
    /**
     * Không cần ghi "Ngày 1" — phần đó tự thêm.
     */
    title: {
      vi: string;
    };
    /**
     * Mỗi dòng là một đoạn văn.
     */
    body: {
      vi: string;
      id?: string | null;
    }[];
    /**
     * Chọn 2 ảnh thì chúng xếp thành hai cột; 1 hoặc 3 ảnh cũng hiển thị được. Nhiều hơn 3 sẽ bị cắt bớt.
     */
    images?: (string | Media)[] | null;
    /**
     * Ví dụ: "Ăn ở đâu", "Ngủ ở đâu", "Những nơi đã ghé". Bỏ trống thì dùng nhãn mặc định.
     */
    locationsLabel?: {
      vi?: string | null;
    };
    locations?: (string | Location)[] | null;
    id?: string | null;
  }[];
  seo: {
    /**
     * Dòng chữ hiện trên tab trình duyệt và trên kết quả tìm kiếm Google. Nên ngắn gọn.
     */
    title: {
      vi: string;
    };
    /**
     * Đoạn tóm tắt hiện dưới tiêu đề trên kết quả tìm kiếm Google và khi chia sẻ link lên Zalo/Facebook.
     */
    description: {
      vi: string;
    };
    ogImage: string | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'tours';
        value: string | Tour;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?:
    | T
    | {
        vi?: T;
        en?: T;
      };
  blurDataURL?: T;
  canhBaoKichThuoc?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        w640?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w1024?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w1600?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w2400?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  slug?: T;
  name?:
    | T
    | {
        vi?: T;
      };
  displayTitle?: T;
  category?: T;
  excerpt?:
    | T
    | {
        vi?: T;
      };
  body?:
    | T
    | {
        vi?: T;
        id?: T;
      };
  address?: T;
  website?: T;
  images?: T;
  seo?:
    | T
    | {
        title?:
          | T
          | {
              vi?: T;
            };
        description?:
          | T
          | {
              vi?: T;
            };
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  slug?: T;
  title?:
    | T
    | {
        vi?: T;
      };
  displayTitle?: T;
  tagline?:
    | T
    | {
        vi?: T;
      };
  summary?:
    | T
    | {
        vi?: T;
      };
  durationDays?: T;
  priceFrom?: T;
  destinations?:
    | T
    | {
        vi?: T;
        id?: T;
      };
  heroMedia?: T;
  gallery?: T;
  itinerary?:
    | T
    | {
        title?:
          | T
          | {
              vi?: T;
            };
        description?:
          | T
          | {
              vi?: T;
            };
        images?: T;
        locations?: T;
        locationsLabel?:
          | T
          | {
              vi?: T;
            };
        id?: T;
      };
  inclusions?:
    | T
    | {
        vi?: T;
        id?: T;
      };
  exclusions?:
    | T
    | {
        vi?: T;
        id?: T;
      };
  notes?:
    | T
    | {
        vi?: T;
      };
  seo?:
    | T
    | {
        title?:
          | T
          | {
              vi?: T;
            };
        description?:
          | T
          | {
              vi?: T;
            };
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  slug?: T;
  title?:
    | T
    | {
        vi?: T;
      };
  displayTitle?: T;
  subtitle?:
    | T
    | {
        vi?: T;
      };
  accent?: T;
  heroImage?: T;
  thumbnail?: T;
  highlights?:
    | T
    | {
        vi?: T;
        id?: T;
      };
  ourRole?:
    | T
    | {
        vi?: T;
        id?: T;
      };
  days?:
    | T
    | {
        title?:
          | T
          | {
              vi?: T;
            };
        body?:
          | T
          | {
              vi?: T;
              id?: T;
            };
        images?: T;
        locationsLabel?:
          | T
          | {
              vi?: T;
            };
        locations?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?:
          | T
          | {
              vi?: T;
            };
        description?:
          | T
          | {
              vi?: T;
            };
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Nội dung hiển thị trên trang chủ. Chỉ có một bản ghi duy nhất.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  hero: {
    headline: {
      vi: string;
    };
    subline: {
      vi: string;
    };
    media: string | Media;
  };
  /**
   * Mỗi lý do gồm một tiêu đề ngắn và một đoạn giải thích.
   */
  whyUs: {
    title: {
      vi: string;
    };
    body: {
      vi: string;
    };
    id?: string | null;
  }[];
  /**
   * Chọn các tour sẽ hiện nổi bật trên trang chủ, từ danh sách tour đã tạo.
   */
  featuredTours: (string | Tour)[];
  journey: {
    headline: {
      vi: string;
    };
    /**
     * Cần tối thiểu 2 điểm đến — hiệu ứng cuộn ngang trên trang chủ không hoạt động với ít hơn 2.
     */
    stops: {
      label: {
        vi: string;
      };
      image: string | Media;
      id?: string | null;
    }[];
  };
  /**
   * Có thể để trống nếu chưa có cảm nhận nào để đăng.
   */
  testimonials?:
    | {
        name: string;
        quote: {
          vi: string;
        };
        /**
         * Không bắt buộc — chỉ chọn nếu cảm nhận này gắn với một tour cụ thể.
         */
        tour?: (string | null) | Tour;
        avatar?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Số thứ tự (01, 02...) tự sinh theo thứ tự trong danh sách — kéo thả để sắp lại, không cần đánh số.
   */
  faq?:
    | {
        question: {
          vi: string;
        };
        answer: {
          vi: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Khối tự giới thiệu hiện dưới biểu mẫu ở trang chủ. Bỏ trống ô Họ tên là cả khối không hiện.
   */
  guide?: {
    name?: string | null;
    role?: {
      vi?: string | null;
    };
    bio?: {
      vi?: string | null;
    };
    photo?: (string | null) | Media;
  };
  contact: {
    phone: string;
    /**
     * URL đầy đủ, ví dụ: https://zalo.me/0901234567
     */
    zaloUrl: string;
    email: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?:
          | T
          | {
              vi?: T;
            };
        subline?:
          | T
          | {
              vi?: T;
            };
        media?: T;
      };
  whyUs?:
    | T
    | {
        title?:
          | T
          | {
              vi?: T;
            };
        body?:
          | T
          | {
              vi?: T;
            };
        id?: T;
      };
  featuredTours?: T;
  journey?:
    | T
    | {
        headline?:
          | T
          | {
              vi?: T;
            };
        stops?:
          | T
          | {
              label?:
                | T
                | {
                    vi?: T;
                  };
              image?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        name?: T;
        quote?:
          | T
          | {
              vi?: T;
            };
        tour?: T;
        avatar?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?:
          | T
          | {
              vi?: T;
            };
        answer?:
          | T
          | {
              vi?: T;
            };
        id?: T;
      };
  guide?:
    | T
    | {
        name?: T;
        role?:
          | T
          | {
              vi?: T;
            };
        bio?:
          | T
          | {
              vi?: T;
            };
        photo?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        zaloUrl?: T;
        email?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}